version: "3"

services:
  xray:
    image: teddysun/xray
    restart: on-failure
    volumes:
      - "./xray:/etc/xray"
      - "./cert:/etc/cert"
      - "./cert_check.sh:/bin/cert_check.sh"
    ports:
      - "443:443"
      - "444:443"
      - "445:443"
      - "446:443"
      - "447:443"
      - "4433:443"
    restart: "unless-stopped"
    # restart hack
    healthcheck:
      test: "kill 1"
      interval: 24h
      start_period: 3s
  caddy:
    restart: on-failure
    image: "caddy"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - 80:80
  tg:
    restart: on-failure
    image: telegrammessenger/proxy
    ports:
      - "2333:443"
    env_file:
      - tg.env

