version: "3"

services:
  xray:
    image: teddysun/xray
    restart: on-failure
    volumes:
      - "./xray:/etc/xray"
      - "./cert:/etc/cert"
      - "./cert_check.sh:/bin/cert_check.sh"
    ports:
      - "443:2023"
  caddy:
    restart: on-failure
    image: "caddy"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "80:80"
  tg:
    restart: on-failure
    image: telegrammessenger/proxy
    ports:
      - "2333:443"
    env_file:
      - tg.env

