version: "3"

services:
  xray:
    image: teddysun/xray:1.8.9
    restart: on-failure
    volumes:
      - "./xray:/etc/xray"
      - "./cert:/etc/cert"
      - "./cert_check.sh:/bin/cert_check.sh"
    ports:
      - "443:443"
      - "444:443"
      - "445:443"
      - "446:443"
      - "447:443"
      - "448:443"
      - "449:443"
      - "450:443"
      - "451:443"
      - "452:443"
      - "453:443"
      - "454:443"
      - "455:443"
      - "4433:443"
  caddy:
    restart: on-failure
    image: "caddy"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "80:80"
  tg:
    restart: on-failure
    image: telegrammessenger/proxy
    ports:
      - "2333:443"
    env_file:
      - tg.env

